{% set name = "pyopensky" %}
{% set version = "2.14" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyopensky-{{ version }}.tar.gz
  sha256: dd121a8dc86de9d82562f4d012c4a0789aed4c8bdc32f79777f801104ba822c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.2
    - trino-python-client >=0.329
    - minio >=7.2.8
    - appdirs >=1.4.4
    - tqdm >=4.66.5
    - pyarrow >=17.0.0
    - typing-extensions >=4.12.2
    - pyjwt >=2.9.0
    - sqlalchemy >=1.3
    - httpx >=0.27.2

test:
  imports:
    - pyopensky
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-aviation/pyopensky
  summary: A Python interface for OpenSky database
  license: LGPL-3.0-or-later
  license_file: license.txt

extra:
  recipe-maintainers:
    - xoolive
