{% set name = "pyopensky" %}
{% set version = "2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyopensky-{{ version }}.tar.gz
  sha256: 828cdc50f6fe409dba50e4099a7e6f3c6362e121cc8fdeed45ae59c617a94a02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pandas >=1.5
    - trino-python-client >=0.322
    - minio >=7.1
    - appdirs >=1.4.4
    - tqdm >=4.65.0
    - pyarrow >=11.0.0
    - typing-extensions >=4.5.0
    - pyjwt >=2.7.0
    - sqlalchemy >=1.3
    - httpx >=0.27.0

test:
  imports:
    - pyopensky
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-aviation/pyopensky
  summary: A Python interface for OpenSky database
  license: LGPL-3.0-or-later
  license_file: license.txt

extra:
  recipe-maintainers:
    - xoolive
